### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by MPleskunina** [JetBrains/resharper-presentation-assistant#37]
JetBrains PresentationAssistant 2021.3.0
ReSharper 2021.3.3

```
Install completed with 3 errors.
  19:42:59.777 ReSharperPlatformVs17_1c4a5cae: The assembly “JetBrains.PresentationAssistant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null” is marked by more than one VS zone: (2pcs)[JetBrains.VsIntegration.Shell.Zones.IVisualStudioFrontendEnvZone, JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11FrontEnvZone]. Highest selected: JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11FrontEnvZone.
  19:42:59.848 ReSharperPlatformVs17_1c4a5cae: The assembly “JetBrains.PresentationAssistant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null” is marked by more than one VS zone: (2pcs)[JetBrains.VsIntegration.Shell.Zones.IVisualStudioFrontendEnvZone, JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11FrontEnvZone]. Highest selected: JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11FrontEnvZone.
  19:42:59.849 ReSharperPlatformVs17_1c4a5cae: The assembly “JetBrains.PresentationAssistant, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null” is marked by more than one VS zone: (2pcs)[JetBrains.VsIntegration.Shell.Zones.IVisualStudioFrontendEnvZone, JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11FrontEnvZone]. Highest selected: JetBrains.Platform.VisualStudio.SinceVs11.Shell.Zones.ISinceVs11FrontEnvZone.
```

**Comment by matkoch** [comment]
```
System.Windows.Markup.XamlParseException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetPropertyDeclaringType(Int16 propertyId)
   at System.Windows.Baml2006.Baml2006Reader.GetStaticExtensionValue(Int16 valueId, Type& memberType, Object& providedValue)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyWithExtension()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at JetBrains.ReSharper.Plugins.PresentationAssistant.PresentationAssistantWindow.InitializeComponent() in C:\code\resharper-presentation-assistant\src\dotnet\JetBrains.PresentationAssistant\PresentationAssistantWindow.xaml:line 1
   at JetBrains.ReSharper.Plugins.PresentationAssistant.PresentationAssistantWindow..ctor() in C:\code\resharper-presentation-assistant\src\dotnet\JetBrains.PresentationAssistant\PresentationAssistantWindow.xaml.cs:line 9
   at JetBrains.ReSharper.Plugins.PresentationAssistant.PresentationAssistantWindowOwner.EnableShortcuts(Lifetime enabledLifetime) in C:\code\resharper-presentation-assistant\src\dotnet\JetBrains.PresentationAssistant\PresentationAssistantWindowOwner.cs:line 51
   at JetBrains.Lifetimes.LifetimeDefinition.ExecuteOrTerminateOnFail(Action`1 atomicAction)
```

**Comment by Mike-E-angelo** [comment]
+1 :P

Things like this make me wonder if I am the only one testing (i.e. using :)) ReSharper.  Glad to see others are sharing my grief.

Really quite unacceptable obvious installation errors are occurring for many weeks at a time now for an officially sanctioned extension, in any case.

**Comment by matkoch** [comment]
@Mike-E-angelo it's a division of labor :) I updated the plugin, and @MPleskunina was going through the installation process in ReSharper (I only work on Windows when necessary).

In this case, there was (roughly speaking) a refactoring for making the SDK more VS-independent. In the first round, we've added a new method that we hoped would solve the issue. Now it shows, that there's a circular dependency which we didn't notice. So as of now, I can't give an estimate of when it will be fixed, but we're definitely on it.

**Comment by Mike-E-angelo** [comment]
Thank you for dealing with my unyielding frustration during these trying times @matkoch 😁  It's been an especially rough patch lately, ugh.  I definitely appreciate all the work you do out there, as well as the team.  I also try to keep focused on what does work which is _quite a lot_.  But still, sometimes it's difficult as you may know.  Anyways, thank you again for your efforts. 🙏

**Comment by Mike-E-angelo** [comment]
I can confirm that it does indeed now work, @matkoch.  Thank you again for your time and patience out there. 👍
